name: 'Github actions copy files to other repositories'
description: 'Will be used to copy files from working location to another repositories'
inputs:
  SOURCE_DIR:
    description: 'source directory'
    required: true
  DESTINATION_REPOS_BRANCHES:
    description: 'destinations repo and branches list'
    required: true
  COMMIT_MESSAGE:
    description: 'commit message'
    required: true
  TAG_NAME:
    description: 'tag name to create'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SOURCE_DIR }}
    - ${{ inputs.DESTINATION_REPOS_BRANCHES }}
    - ${{ inputs.COMMIT_MESSAGE }}
    - ${{ inputs.TAG_NAME }}
branding:
  icon: 'git-commit'
  color: 'green'